---
- hosts: private_deploy
  name: Install Jenkins and Docker on Private Slave EC2
  remote_user: ubuntu
  become: yes
  vars:
    ssh_public_key: "{{ lookup('file', './ssh_public_key.pub') }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install curl and gnupg
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg

    - name: Add Jenkins APT keyring
      shell: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc"

    - name: Add Jenkins APT repository
      shell: "echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list"

    - name: Update apt cache after adding Jenkins repository
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jre
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Create Jenkins user
      user:
        name: jenkins
        shell: /bin/bash
        system: yes

    - name: Create Jenkins directory
      file:
        path: /home/jenkins
        state: directory

    - name: Change ownership of /home/jenkins
      file:
        path: /home/jenkins
        owner: jenkins
        group: jenkins
        recurse: yes

    - name: Create .ssh directory for Jenkins user
      file:
        path: /home/jenkins/.ssh
        state: directory

    - name: Add SSH public key to authorized_keys for jenkins user
      authorized_key:
        user: jenkins
        key: "{{ ssh_public_key }}"
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Import Docker GPG Key from Local File
      apt_key:
        data: "{{ lookup('file', '/home/zeinab/Downloads/Jenkins-Project-test/gpg') }}"
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Add Jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes
