---
- hosts: infra
  name: Install Jenkins and Terraform on Slave EC2
  remote_user: ubuntu
  become: yes

  tasks:
    # Install Jenkins
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install curl and gnupg
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg

    - name: Add Jenkins APT keyring
      shell: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc"

    - name: Add Jenkins APT repository
      shell: "echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list"

    - name: Update apt cache after adding Jenkins repository
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-17-jre
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Create Jenkins user
      user:
        name: jenkins
        shell: /bin/bash
        system: yes

    - name: Create Jenkins directory
      file:
        path: /home/ubuntu/jenkins
        state: directory
        mode: "0777"

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    # Install Terraform
    - name: Import HashiCorp GPG key
      shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

    - name: Add HashiCorp APT repository
      shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list

    - name: Update apt cache after adding HashiCorp repository
      apt:
        update_cache: yes

    - name: Install Terraform
      apt:
        name: terraform
        state: present
